name: pr-title

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

permissions: {}

jobs:
  pr-title:
    if: ${{ !github.event.repository.is_template }}
    permissions:
      contents: read
      pull-requests: read
    uses: ./.github/workflows/reusable-pr-title.yml
