name: actionlint (reusable)

on:
  workflow_call:

permissions: {}

jobs:
  actionlint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Download actionlint
        id: get-actionlint
        run: bash <(curl -sSfL https://raw.githubusercontent.com/rhysd/actionlint/v1.7.12/scripts/download-actionlint.bash) 1.7.12

      - name: Run actionlint
        run: ${{ steps.get-actionlint.outputs.executable }} -color
